version: '3'
services:
  # MySQL service
  db:
    image: mysql:5.7
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: celln_blog
    ports:
      - "3307:3306"

  # Node.js service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file: ./.env
